// Generated by SwiftGen
import Foundation

public enum testappsStrings {
  // MARK: - App
  public static var appName: String { tr("app.name") }
  
  // MARK: - General
  public static var generalLoading: String { tr("general.loading") }
  public static var generalError: String { tr("general.error") }
  public static var generalRetry: String { tr("general.retry") }
  public static var generalCancel: String { tr("general.cancel") }
  
  // MARK: - Destination List
  public static var destinationsTitle: String { tr("destinations.title") }
  public static var destinationsEmpty: String { tr("destinations.empty") }
  
  // MARK: - Destination Detail
  public static var detailPopulation: String { tr("detail.population") }
  public static var detailPrice: String { tr("detail.price") }
  public static var detailLatitude: String { tr("detail.latitude") }
  public static var detailLongitude: String { tr("detail.longitude") }
  public static func detailPhotographer(_ p1: CVarArg) -> String { tr("detail.photographer", p1) }
  
  // MARK: - Errors
  public static var errorNetworkTitle: String { tr("error.network.title") }
  public static var errorNetworkMessage: String { tr("error.network.message") }
  public static var errorUnknown: String { tr("error.unknown") }
}

extension testappsStrings {
  static func tr(_ key: String, _ args: CVarArg...) -> String {
    let manager = LocalizationContainer.shared()
    return manager.localizedString(for: key, arguments: args)
  }
}
